config/routes.rb
Rails.application.routes.draw do
  get 'herbs/graph_one'

  get 'herbs/graph_two'

  get 'rooms/show'

  # get 'static_pages/home'
  root controller: :static_pages, action: :home

  get 'static_pages/index'

  get 'static_pages/help'

  # get 'euro_happy/index'
  # root controller: :euro_happy, action: :index

	mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

		@messages = Message.all
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  def graph_one
  end

  def graph_two
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
		# @messages = Message.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def index
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/euro_happy_helper.rb
module EuroHappyHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/herbs/graph_one.html.erb
<h1>Herbs#graph_one</h1>
<p>Find me in app/views/herbs/graph_one.html.erb</p>

app/views/herbs/graph_two.html.erb
<h1>Herbs#graph_two</h1>
<p>Find me in app/views/herbs/graph_two.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataSets</title>
    <%= csrf_meta_tags %>
		<%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<script src="https://d3js.org/d3.v4.min.js"></script>
  </head>

	<nav class="navbar navbar-default navbar-expand-sm">
		<%= link_to 'Home', root_path, method: :get %>
		<%= link_to 'Index', static_pages_index_path, method: :get %>
		<%= link_to 'Help', static_pages_help_path, method: :get %>
		<%= link_to 'Rooms#Show', rooms_show_path, method: :get %>
		<%= link_to 'Graph One', herbs_graph_one_path, method: :get %>
		<%= link_to 'Graph Two', herbs_graph_two_path, method: :get %>
	</nav>

  <body>
    <%= yield %>

	<div class="container" style="position: fixed; bottom: 0; right: 0;">
		<h1>Chat room&nbsp;&nbsp;</h1>

		<div id="messages">

		</div>

		<form>
			<label>Say something:</label><br>
			<input type="text" data-behavior="room_speaker">
		</form>
		<br>&nbsp;<br>
	</div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class=“message”>
  <p><%= message.content %></p>
</div>

app/views/rooms/show.html.erb
<!--h1>Chat room</h1>

<div id="messages">

</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form-->

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<script>


</script>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>